# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{theme_engine}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Qichunren"]
  s.date = %q{2011-02-15}
  s.description = %q{An awesome theme engine for rails 3 project}
  s.email = %q{whyruby@gmail.com}
  s.files = [
    "config/routes.rb",
     "lib/theme_engine.rb",
     "lib/theme_engine/engine.rb"
  ]
  s.has_rdoc = false
  s.homepage = %q{http://github.com/qichunren/theme_engine}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An awesome theme engine for rails 3 project}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

